#!/usr/bin/env python3
"""Build an exact reviewed US-097 row-disposition ledger.

The frozen US-089 ownership map remains the authority for rows that existed at
the separation boundary. Every later row must appear in the reviewed
post-baseline allowlist; unknown rows fail instead of inheriting ownership.
"""

from __future__ import annotations

import argparse
import importlib.util
import json
from pathlib import Path
from typing import Any


def load_inventory_module(root: Path):
    path = root / "scripts/e11-us097-inventory.py"
    spec = importlib.util.spec_from_file_location("e11_us097_inventory", path)
    if spec is None or spec.loader is None:
        raise RuntimeError(f"cannot load inventory module: {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def legacy_identity(table: str, values: dict[str, Any]) -> str:
    if values.get("uid"):
        return str(values["uid"])
    if table == "story":
        return str(values["id"])
    if table == "story_dependency":
        return f"{values['story_id']}|{values['blocks_story_id']}"
    if table == "story_hierarchy":
        return f"{values['parent_story_id']}|{values['child_story_id']}"
    if table == "schema_version":
        return str(values["version"])
    if table == "changeset_applied":
        return str(values["id"])
    if table == "tool":
        return str(values["name"])
    if table == "story_backlog_link":
        return f"{values['story_id']}|{values['backlog_uid']}"
    if table == "proposal_evidence_link":
        return f"{values['backlog_uid']}|{values['source_kind']}|{values['evidence_uid']}"
    if "id" in values:
        return str(values["id"])
    raise ValueError(f"no reviewed legacy identity rule for table {table}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", type=Path, required=True)
    parser.add_argument("--source-db", type=Path, required=True)
    parser.add_argument("--policy", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    root = args.repo_root.resolve()
    policy = json.loads(args.policy.read_text())
    baseline_path = root / policy["baseline_ownership_map"]
    baseline_raw = json.loads(baseline_path.read_text())
    baseline = {
        (row["table"], row["identity"]): row for row in baseline_raw["records"]
    }
    post_baseline = {tuple(item) for item in policy["post_baseline_core"]}
    allowed_target_overlap = {tuple(item) for item in policy["allowed_target_overlap"]}
    overrides = {
        (item["table"], item["legacy_identity"]): item
        for item in policy["overrides"]
    }
    inventory = load_inventory_module(root).inventory_database(args.source_db)
    rows = []
    observed_post_baseline = set()
    errors = []
    owner_actions = {
        "repository-harness": "retain-core",
        "coordinated-proxy": "retain-core",
        "shared-migration": "retain-core",
        "symphony": "archive-only",
    }
    for table, detail in inventory["tables"].items():
        for row in detail["rows"]:
            legacy = legacy_identity(table, row["values"])
            key = (table, legacy)
            if table in {"schema_version", "changeset_applied"}:
                disposition = {
                    "action": "derive",
                    "owner": "repository-harness",
                    "reason": "epoch-derived state is regenerated by migrations or content-bound apply",
                }
            elif key in overrides:
                disposition = overrides[key]
            elif key in baseline:
                authority = baseline[key]
                action = owner_actions.get(authority["owner"])
                if action is None:
                    errors.append(f"unsupported baseline owner {authority['owner']} for {table} {legacy}")
                    continue
                disposition = {
                    "action": action,
                    "owner": authority["owner"],
                    "reason": authority["reason"],
                }
            elif key in post_baseline:
                observed_post_baseline.add(key)
                disposition = {
                    "action": "retain-core",
                    "owner": "repository-harness",
                    "reason": "reviewed post-baseline E11 core or source-coordination evidence",
                }
            else:
                errors.append(f"unreviewed post-baseline row {table} {legacy}")
                continue
            rows.append({
                "table": table,
                "identity": row["identity"],
                "legacy_identity": legacy,
                "action": disposition["action"],
                "owner": disposition["owner"],
                "reason": disposition["reason"],
                "allow_target_overlap": key in allowed_target_overlap,
                **({"target_identity": disposition["target_identity"]} if "target_identity" in disposition else {}),
            })
    missing = sorted(post_baseline - observed_post_baseline)
    if missing:
        errors.extend(f"reviewed post-baseline row is absent: {table} {identity}" for table, identity in missing)
    missing_overlap = sorted(allowed_target_overlap - {
        (row["table"], row["legacy_identity"]) for row in rows
    })
    if missing_overlap:
        errors.extend(f"allowed target overlap is absent: {table} {identity}" for table, identity in missing_overlap)
    if errors:
        raise ValueError("; ".join(errors))
    output = {
        "version": 1,
        "source_db_sha256": inventory["sha256"],
        "baseline_logical_sha256": baseline_raw["database_logical_sha256"],
        "row_count": len(rows),
        "rows": sorted(rows, key=lambda item: (item["table"], item["identity"])),
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(output, indent=2, sort_keys=True) + "\n")
    print(f"US-097 disposition ledger written: {len(rows)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
